# Playbook apache.yml
---
- name: Installing Apache service 
  hosts: 100.80.5.202                                  # Define all the hosts
  remote_user: ubuntu                                    # Remote_user is ubuntu
  # Defining the Ansible task
  tasks:                                                 
  - name: Install the Latest Apache
    apt:
      name: httpd
      state: latest
